services:
  nix:
    image: nixos/nix:2.22.3
    platform: linux/amd64
    container_name: nixos-homelab-dev
    volumes:
      - .:/workspace
      - ~/.config/sops:/root/.config/sops
      - nix-store:/nix/store
      - cache:/root/.cache/nix
      - var:/nix/var
    working_dir: /workspace
    stdin_open: true
    tty: true
    environment:
      NIX_CONFIG: |
        experimental-features = nix-command flakes
        access-tokens = github.com=${GITHUB_TOKEN:-}
        filter-syscalls = false
        sandbox = false

volumes:
  nix-store:
  cache:
  var:
