services:
  nix:
    image: nixos/nix
    platform: linux/amd64
    container_name: nixos-homelab-builder
    volumes:
      - .:/build
      - ~/.config/sops:/var/lib/sops-nix:ro
      - nix-store:/nix/store
    working_dir: /build
    command: sleep infinity
    environment:
      NIX_CONFIG: |
        experimental-features = nix-command flakes
        access-tokens = github.com=${GITHUB_TOKEN:-}
        filter-syscalls = false

volumes:
  nix-store:
    driver: local
