services:
  nix:
    image: nixos/nix
    container_name: nix_container
    volumes:
      - nix-data:/nix/var/nix
      - nix-store:/nix/store
    command: sleep infinity
    environment:
      NIX_PATH: /nix/store
      NIX_CONFIG: |
        experimental-features = nix-command flakes
        access-tokens = github.com=${GITHUB_TOKEN}
        filter-syscalls = false

volumes:
  nix-data:
    driver: local
  nix-store:
    driver: local
